export const INIT_APPLICATION = 'INIT_APPLICATION';
export const APPLICATION_INITIALIZED = 'APPLICATION_INITIALIZED';

export const INCREMENT_LIKES = 'INCREMENT_LIKES';

export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
